# Generated by Django 3.2.15 on 2022-10-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_follow_subscribe'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingList',
            new_name='ShoppingCard',
        ),
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(help_text='Введите цвет кода', max_length=32, unique=True, verbose_name='Цвет кода'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(help_text='Введите имя тега', max_length=128, unique=True, verbose_name='Название тега'),
        ),
    ]
