# Generated by Django 2.2.16 on 2022-10-02 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=128, unique=True)),
                ('second_name', models.CharField(help_text='Введите фамилию', max_length=128, unique=True)),
                ('username', models.CharField(help_text='Введите логин', max_length=128, unique=True)),
                ('email', models.EmailField(help_text='Введите эмейл', max_length=128, unique=True)),
                ('password', models.CharField(help_text='Введите пароль', max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользоватили',
                'ordering': ('username',),
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(help_text='Выберите автора', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.Users', verbose_name='Автор')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.Users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
