# Generated by Django 3.2.15 on 2022-10-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Subscribe',
        ),
    ]
